services:
  projects-front:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./.env
    volumes:
      - ./src:/app/src
    environment:
      - NUXT_PUBLIC_APP_API_URL:${NUXT_PUBLIC_APP_API_URL}
      - NUXT_PUBLIC_APP_KEYCLOAK_URL:${NUXT_PUBLIC_APP_KEYCLOAK_URL}
    ports:
      - 8080:8080
