version: '3'
services:
    projects-front:
        platform: linux/amd64
        build:
            context: .
            args:
                NUXT_PUBLIC_APP_API_URL: http://localhost:8000
                NUXT_PUBLIC_APP_CAPTCHA_KEY: 6Lej3a4UAAAAAFzSbSGrznwFxeZzH0PXdrcTb7kN
                NUXT_PUBLIC_APP_DOC: https://docs.projects.k8s.lp-i.dev/
                NUXT_PUBLIC_APP_KEYCLOAK_URL: http://localhost:8001
                NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: projects-backend-local
                NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: 03nfDv4dHCc97w7E4uvtdyiW4xVD6GYw
                NUXT_PUBLIC_APP_META_PORTAL_URL: https://projects.k8s.lp-i.dev
                NUXT_PUBLIC_APP_MIXPANEL_API_URL: https://mixpanel-proxy.k8s.lp-i.dev
        ports:
            - 8080:8080
