FROM node:22

WORKDIR /app

# COPY package.json yarn.lock /app/

# RUN yarn install --pure-lockfile --non-interactive &&\
#     rm -rf /usr/local/share/.cache

ARG NUXT_PUBLIC_APP_API_DEFAULT_VERSION=/v1 \
    NUXT_PUBLIC_APP_API_ORG_CODE=CRI \
    NUXT_PUBLIC_APP_API_URL=https://api.projects.k8s.lp-i.dev \
    NUXT_PUBLIC_APP_BASE_URL \
    NUXT_PUBLIC_APP_CAPTCHA_KEY=6Lej3a4UAAAAAFzSbSGrznwFxeZzH0PXdrcTb7kN \
    NUXT_PUBLIC_APP_CURRENTTHEME="" \
    NUXT_PUBLIC_APP_DOC=https://docs.projects.k8s.lp-i.dev/ \
    NUXT_PUBLIC_APP_I18N_FALLBACK_LOCALE=en \
    NUXT_PUBLIC_APP_I18N_LOCALE=fr \
    NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID \
    NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET \
    NUXT_PUBLIC_APP_KEYCLOAK_REALM=lp \
    NUXT_PUBLIC_APP_KEYCLOAK_URL=https://id.learning-planet.org/auth \
    NUXT_PUBLIC_APP_MAX_SIZE_FILE=5000000 \
    NUXT_PUBLIC_APP_META_PORTAL_URL=https://projects.directory \
    NUXT_PUBLIC_APP_MIXPANEL_API_URL \
    NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN \
    NUXT_PUBLIC_APP_PUBLIC_BINARIES_PREFIX=https://criparisprodprodassets.blob.core.windows.net/assets/public \
    NUXT_PUBLIC_APP_VERSION\
    NUXT_PUBLIC_APP_WELEARNSRV=https://welearn.cri-paris.org \
    NUXT_PUBLIC_APP_WSS_HOST=cri.projects.k8s.lp-i.dev\
    NUXT_PUBLIC_APP_MIXPANEL_API_HOST\
    NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN

EXPOSE 8080 3010 3020

CMD ["yarn" ,"serve"]
