apiVersion: v1
kind: Service
metadata:
  labels:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
  name: {{ tpl .Values.fullName . }}
spec:
  selector:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
