import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'
import SorbobotAPI from '@/mcp-server/sorbobot/sorbobot-api.js'

// TODO people group member and project
// TODO org files
// TODO pagination of search results
// TODO output schemas

const API_BASE_URL = 'https://api.projects.k8s.lp-i.dev/v1/'

const runtimeConfig = useRuntimeConfig()
const orgCode = runtimeConfig.public.appApiOrgCode
// Create an MCP server
const server = new McpServer({
  name: 'demo-server',
  version: '1.0.0',
})

let sorbobotApi: SorbobotAPI | null = null
const sorbobotApiUrl = runtimeConfig.public.appSorbobotApiUrl
const sorbobotApiToken = runtimeConfig.appSorbobotApiToken
// console.log(
//   'Sorbobot config',
//   'sorbobotApiUrl',
//   !!sorbobotApiUrl,
//   'sorbobotApiToken',
//   !!sorbobotApiToken
// )
if (sorbobotApiUrl && sorbobotApiToken) {
  sorbobotApi = new SorbobotAPI(sorbobotApiToken, sorbobotApiUrl)
  console.log('Sorbobot API initialized')
}
// generated by perplexity
const ALL_SDGS = [
  { id: 1, title: 'No poverty', description: 'End poverty in all its forms everywhere.' },
  {
    id: 2,
    title: 'Zero hunger',
    description:
      'End hunger, achieve food security and improved nutrition and promote sustainable agriculture.',
  },
  {
    id: 3,
    title: 'Good health and well-being',
    description: 'Ensure healthy lives and promote well-being for all at all ages.',
  },
  {
    id: 4,
    title: 'Quality education',
    description:
      'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.',
  },
  {
    id: 5,
    title: 'Gender equality',
    description: 'Achieve gender equality and empower all women and girls.',
  },
  {
    id: 6,
    title: 'Clean water and sanitation',
    description: 'Ensure availability and sustainable management of water and sanitation for all.',
  },
  {
    id: 7,
    title: 'Affordable and clean energy',
    description: 'Ensure access to affordable, reliable, sustainable and modern energy for all.',
  },
  {
    id: 8,
    title: 'Decent work and economic growth',
    description:
      'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all.',
  },
  {
    id: 9,
    title: 'Industry, innovation and infrastructure',
    description:
      'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation.',
  },
  {
    id: 10,
    title: 'Reduced inequalities',
    description: 'Reduce inequality within and among countries.',
  },
  {
    id: 11,
    title: 'Sustainable cities and communities',
    description: 'Make cities and human settlements inclusive, safe, resilient and sustainable.',
  },
  {
    id: 12,
    title: 'Responsible consumption and production',
    description: 'Ensure sustainable consumption and production patterns.',
  },
  {
    id: 13,
    title: 'Climate action',
    description: 'Take urgent action to combat climate change and its impacts.',
  },
  {
    id: 14,
    title: 'Life below water',
    description:
      'Conserve and sustainably use the oceans, seas and marine resources for sustainable development.',
  },
  {
    id: 15,
    title: 'Life on land',
    description:
      'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss.',
  },
  {
    id: 16,
    title: 'Peace, justice and strong institutions',
    description:
      'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels.',
  },
  {
    id: 17,
    title: 'Partnerships for the goals',
    description:
      'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development.',
  },
].map((sdg) => ({
  ...sdg,
  item_image: `${runtimeConfig.public.appPublicBinariesPrefix}/sdgs/en/${sdg.id}.svg`,
}))

const mapNewsArticle = (n: any) => ({
  id: n.id,
  slug: n.slug,
  title: n.title,
  content: n.content,
  publication_date: n.publication_date,
})

const mapInstructionArticle = (i: any) => ({
  id: i.id,
  slug: i.slug,
  title: i.title,
  content: i.content,
  publication_date: i.publication_date,
})

const mapEvent = (e: any) => ({
  id: e.id,
  slug: e.slug,
  title: e.title,
  content: e.content,
  event_date: e.event_date,
})

const mapSDG = (s: any) => {
  return ALL_SDGS[s] || { id: s }
}

const categoryMapper = (c: any) => ({ id: c.id, slug: c.slug, name: c.name })

const tagMapper = (t: any) => ({ id: t.id, title: t.title, description: t.description })

const mapProjectPreview = (p: any) => ({
  id: p.id,
  slug: p.slug,
  title: p.title,
  purpose: p.purpose,
  categories: (p.categories || []).map(categoryMapper),
  link_url: `/projects/${p.slug}/`,
  item_image: p.header_image?.variations?.small,
})

const mapUserPreview = (u: any) => ({
  id: u.id,
  slug: u.slug,
  given_name: u.given_name,
  family_name: u.family_name,
  job: u.job,
  email: u.email,
  link_url: `/profile/${u.slug}/`,
  item_image: u.profile_picture?.variations?.small,
})

const mapPeopleGroupPreview = (g: any) => ({
  id: g.id,
  slug: g.slug,
  name: g.name,
  short_description: g.short_description,
  description: g.description,
  email: g.email,
  member_count: g.member_count,
  link_url: `/group/${g.slug}/`,
  item_image: g.header_image?.variations?.small,
})

const mapBlogEntry = (b: any) => ({
  id: b.id,
  title: b.title,
  content: b.content,
})

// Add an search tool
server.registerTool(
  'all-sdgs',
  {
    title: 'LList of all SDGs Sustainable Development Goals',
    description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
    inputSchema: {},
    outputSchema: { results: z.array(z.any()) },
  },
  async () => {
    const output = { results: ALL_SDGS }
    // console.log('MCP TOOL CALLED: search', { query, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

server.registerTool(
  'sdgById',
  {
    title: 'LList of all SDGs Sustainable Development Goals',
    description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
    inputSchema: { sdgId: z.number() },
    outputSchema: { results: z.any() },
  },
  async ({ sdgId }) => {
    let results: any = {}
    try {
      results = ALL_SDGS[sdgId] || 'SDG not found'
    } catch (error) {
      console.error('Error fetching search results:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: search', { query, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'search',
  {
    title: 'Search Tool',
    description: 'Search on the platform for projects, people and groups related to a query.',
    inputSchema: { queryTerms: z.string() },
    outputSchema: { results: z.array(z.any()) },
  },
  async ({ queryTerms }) => {
    let results = []
    try {
      const query = {
        limit: 12,
        organizations: [orgCode],
      }
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}search/${encodeURIComponent(queryTerms)}/?limit=30&organizations=${orgCode}`,
        { query }
      )
      results = queryResult.results.map((item) => {
        if (item.type === 'project') {
          const p = item.project
          return mapProjectPreview(p)
        } else if (item.type === 'user') {
          const u = item.user
          return mapUserPreview(u)
        } else if (item.type === 'people_group') {
          const g = item.people_group
          return mapPeopleGroupPreview(g)
        }
      })
    } catch (error) {
      console.error('Error fetching search results:', error)
    }
    const output = { results } // skip pagination for simplicity
    // console.log('MCP TOOL CALLED: search', { query, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'project-general-data',
  {
    title: 'Project general data',
    description:
      'Get main general data about a project given its id or slug. To get the project id or slug, use the search tool with the project name, the project id or slug will be in the first result.',
    inputSchema: { idOrSlug: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}project/${idOrSlug}/`
      )
      const p = queryResult
      results = {
        id: p.id,
        item_image: p.header_image?.variations?.small,
        slug: p.slug,
        title: p.title,
        description: p.description,
        sdgs: (p.sdgs || []).map(mapSDG),
        purpose: p.purpose,
        tags: (p.tags || []).map(tagMapper),
        categories: (p.categories || []).map(categoryMapper),
        goals: (p.goals || []).map((g: any) => ({
          id: g.id,
          title: g.title,
          description: g.description,
          status: g.status,
        })),
        reviews: (p.reviews || []).map((r: any) => ({
          r: r.id,
          title: r.title,
          description: r.description,
          reviewer: r.reviewer
            ? {
                id: r.reviewer.id,
                given_name: r.reviewer.given_name,
                family_name: r.reviewer.family_name,
              }
            : null,
        })),
        locations: (p.locations || []).map((l: any) => ({
          id: l.id,
          title: l.title,
          description: l.description,
          type: l.type,
          lat: l.lat,
          lng: l.lng,
        })),
        announcements: (p.announcements || []).map((a: any) => ({
          id: a.id,
          title: a.title,
          description: a.description,
          status: a.status,
          deadline: a.deadline,
          is_remunerated: a.is_remunerated,
        })),
        links: (p.links || []).map((link: any) => ({
          id: link.id,
          title: link.title,
          category: link.category,
          description: link.description,
          site_name: link.site_name,
          site_url: link.site_url,
        })),
        files: (p.files || []).map((file: any) => ({
          id: file.id,
          title: file.title,
          description: file.description,
          file: file.file,
          mime: file.mime,
        })),
        blog_entries: (p.blog_entries || []).map(mapBlogEntry),
        linked_projects: (p.linked_projects || []).map(mapProjectPreview),
        views: p.views,
        team: {
          members: (p.team?.members || []).map(mapUserPreview),
          owners: (p.team?.owners || []).map(mapUserPreview),
          reviewers: (p.team?.reviewers || []).map(mapUserPreview),
          member_groups: (p.team?.member_groups || []).map(mapPeopleGroupPreview),
          owner_groups: (p.team?.owner_groups || []).map(mapPeopleGroupPreview),
          reviewer_groups: (p.team?.reviewer_groups || []).map(mapPeopleGroupPreview),
        },
      }
    } catch (error) {
      console.error('Error fetching project general data:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: project-general-data', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'project-similar',
  {
    title: 'Project similar projects',
    description:
      'Get projects that are similar to the one given by its id or slug. To get the project id or slug, use the search tool with the project name, the project id or slug will be in the first result.',
    inputSchema: { idOrSlug: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}project/${idOrSlug}/similar/`
      )
      results = queryResult.results.map((p: any) => mapProjectPreview(p))
    } catch (error) {
      console.error('Error fetching project similar projects:', error)
    }
    const output = { results }
    console.log('MCP TOOL CALLED: project-similar-projects', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'project-blog-entries',
  {
    title: 'Project blog entries',
    description:
      'Get main blog entries about a project given its id or slug. To get the project id or slug, use the search tool with the project name, the project id or slug will be in the first result.',
    inputSchema: { idOrSlug: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}project/${idOrSlug}/blog-entry/`
      )
      results = queryResult.results.map(mapBlogEntry)
    } catch (error) {
      console.error('Error fetching project blog entries:', error)
    }
    const output = { results }
    console.log('MCP TOOL CALLED: project-blog-entries', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'project-blog-entry',
  {
    title: 'Project blog entries',
    description:
      'Get main blog entries about a project given its id or slug. To get the project id or slug, use the search tool with the project name, the project id or slug will be in the first result. You can get all blog entries of a project and their id using project-blog-entries tool.',
    inputSchema: { idOrSlug: z.string(), blogEntryId: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug, blogEntryId }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}project/${idOrSlug}/blog-entry/${blogEntryId}/`
      )
      results = mapBlogEntry(queryResult)
    } catch (error) {
      console.error('Error fetching project blog entry:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: project-blog-entry', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'people-general-data',
  {
    title: 'People general data',
    description:
      'Get main general data about a people profile given its id or slug. To get the profile id or slug, use the search tool with the profile name, the profile id or slug will be in the first result.',
    inputSchema: { idOrSlug: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}user/${idOrSlug}/`
      )
      const u = queryResult
      results = {
        id: u.id,
        item_image: u.profile_picture?.variations?.small,
        slug: u.slug,
        is_superuser: u.is_superuser,
        people_groups: (u.people_groups || []).map(mapPeopleGroupPreview),
        skills: (u.skills || []).map((s) => ({
          id: s.id,
          tag: tagMapper(s.tag),
          level: s.level,
          level_to_reach: s.level_to_reach,
          type: s.type,
          can_mentor: s.can_mentor,
          needs_mentor: s.needs_mentor,
          comment: s.comment,
        })),
        given_name: u.given_name,
        family_name: u.family_name,
        short_description: u.short_description,
        description: u.description,
        location: u.location,
        job: u.job,
        email: u.email,
        facebook: u.facebook,
        linkedin: u.linkedin,
        website: u.website,
        sdgs: (u.sdgs || []).map(mapSDG),
      }
      results = queryResult
    } catch (error) {
      console.error('Error fetching profile general data:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: profile-general-data', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'people-group-data',
  {
    title: 'People group data',
    description:
      'Get main general data about a people group given its id or slug. To get the group id or slug, use the search tool with the group name, the group id or slug will be in the first result.',
    inputSchema: { idOrSlug: z.string() },
    outputSchema: { results: z.object({}) },
  },
  async ({ idOrSlug }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/people-group/${idOrSlug}/`
      )
      const g = queryResult
      results = {
        id: g.id,
        item_image: g.header_image?.variations?.small,
        slug: g.slug,
        name: g.name,
        description: g.description,
        short_description: g.short_description,
        email: g.email,
        hierarchy: (g.hierarchy || []).map(mapPeopleGroupPreview),
        children: (g.children || []).map(mapPeopleGroupPreview),
      }
    } catch (error) {
      console.error('Error fetching group general data:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: people-group-data', { idOrSlug, output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'organization-data',
  {
    title: 'Organization general data',
    description: 'Get main general data about the platform organization. ',
    inputSchema: {},
    outputSchema: { results: z.object({}) },
  },
  async () => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/`
      )
      const org = queryResult
      results = {
        id: org.id,
        code: org.code,
        terms_and_confitions: org.terms_and_conditions?.displayed_content || '',
        name: org.name,
        contact_email: org.contact_email,
        dashboard_title: org.dashboard_title,
        dashboard_subtitle: org.dashboard_subtitle,
        description: org.description,
        website_url: org.website_url,
      }
    } catch (error) {
      console.error('Error fetching organization general data:', error)
    }
    const output = results
    // console.log('MCP TOOL CALLED: organization-general-data', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'organization-featured-projects',
  {
    title: 'Organization featured projects',
    description: 'Get a list of featured projects for the platform organization.',
    inputSchema: {},
    outputSchema: { results: z.object({}) },
  },
  async () => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/featured-projects/`
      )
      results = queryResult.results.map((p: any) => mapProjectPreview(p))
    } catch (error) {
      console.error('Error fetching organization featured projects:', error)
    }
    const output = { results }
    // console.log('MCP TOOL CALLED: organization-featured-projects', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'news-list',
  {
    title: 'News list',
    description: 'Get a list of news articles.',
    inputSchema: {},
    outputSchema: { results: z.array(z.object({})) },
  },
  async () => {
    const params = { ordering: '-publication_date', limit: 30, to_date: new Date().toISOString() }
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/news/`,
        { params }
      )
      results = queryResult.results.map(mapNewsArticle)
    } catch (error) {
      console.error('Error fetching organization news list:', error)
    }
    const output = { results }
    console.log('MCP TOOL CALLED: news-list', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'news-article',
  {
    title: 'News data',
    description: 'Get a news article. Use the news-list tool to get news ids.',
    inputSchema: { slugOrId: z.string() },
    outputSchema: { results: z.array(z.object({})) },
  },
  async ({ slugOrId }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/news/${slugOrId}/`
      )
      results = mapNewsArticle(queryResult.results)
    } catch (error) {
      console.error('Error fetching organization news item:', error)
    }
    const output = results
    console.log('MCP TOOL CALLED: news-article', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'instructions-list',
  {
    title: 'Instructions list',
    description: 'Get a list of instructions  .',
    inputSchema: {},
    outputSchema: { results: z.array(z.object({})) },
  },
  async () => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/instruction/`
      )
      results = queryResult.results.map(mapInstructionArticle)
    } catch (error) {
      console.error('Error fetching organization instructions list:', error)
    }
    const output = { results }
    console.log('MCP TOOL CALLED: instructions-list', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'instruction-article',
  {
    title: 'Instruction data',
    description:
      'Get an instruction article. Use the instructions-list tool to get instruction ids.',
    inputSchema: { slugOrId: z.string() },
    outputSchema: { results: z.array(z.object({})) },
  },
  async ({ slugOrId }) => {
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/instruction/${slugOrId}/`
      )
      results = mapInstructionArticle(queryResult.results)
    } catch (error) {
      console.error('Error fetching organization instruction item:', error)
    }
    const output = results
    console.log('MCP TOOL CALLED: instruction-article', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'future-events-list',
  {
    title: 'Future Events list',
    description: 'Get a list of future events.',
    inputSchema: {},
    outputSchema: { results: z.array(z.object({})) },
  },
  async () => {
    // today date at midnight
    const todayZeroHour = new Date()
    todayZeroHour.setHours(0, 0, 0, 0)
    const params = {
      ordering: 'event_date',
      from_date: todayZeroHour.toISOString(),
    }
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/event/`,
        { params }
      )
      results = queryResult.results.map(mapEvent)
    } catch (error) {
      console.error('Error fetching organization future events list:', error)
    }
    const output = { results }
    console.log('MCP TOOL CALLED: future- events-list', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

// Add an search tool
server.registerTool(
  'past-events-list',
  {
    title: 'Past Events list',
    description: 'Get a list of past events.',
    inputSchema: {},
    outputSchema: { results: z.array(z.object({})) },
  },
  async () => {
    // today date at midnight
    const todayZeroHour = new Date()
    todayZeroHour.setHours(0, 0, 0, 0)
    const params = {
      ordering: '-event_date',
      to_date: todayZeroHour.toISOString(),
    }
    let results = {}
    try {
      const queryResult: any = await $fetch(
        // TODO: use org code from config
        `${API_BASE_URL}organization/${orgCode}/event/`,
        { params }
      )
      results = mapEvent(queryResult.results)
    } catch (error) {
      console.error('Error fetching organization past events list:', error)
    }
    const output = results
    console.log('MCP TOOL CALLED: past-events-list', { output })
    return {
      content: [{ type: 'text', text: JSON.stringify(output) }],
      structuredContent: output,
    }
  }
)

if (sorbobotApi) {
  // console.log('Registering Sorbobot API tool')
  // Add an search tool
  server.registerTool(
    'sorbobot-api',
    {
      title: 'Research, researchers, experts and science topics and publication finder',
      description:
        'Get a list of researchers and their research papers based on a query. Also get a list of research topics.',
      inputSchema: { queryPrompt: z.string() },
      outputSchema: { researchers: z.array(z.object({})), research_topics: z.array(z.string()) },
    },
    async ({ queryPrompt }) => {
      let results = { researchers: [], research_topics: [] }
      if (!sorbobotApi) {
        console.log('Sorbobot API not initialized')
        return results
      }
      try {
        await sorbobotApi.init()
        const sorbobotResults = await sorbobotApi.query(queryPrompt)
        await sorbobotApi.close()
        results = {
          researchers: Object.entries(sorbobotResults.authors).map((entry) => entry[1]),
          research_topics: sorbobotResults.search_results,
        }
      } catch (error) {
        console.error('Error querying Sorbobot:', error)
      }
      const output = results
      // console.log('MCP TOOL CALLED: sorbobot-api', { output })
      return {
        content: [{ type: 'text', text: JSON.stringify(output) }],
        structuredContent: output,
      }
    }
  )
}

export default server
