process.env.NUXT_APP_CHATBOT_PROMPT_DB = 'postgresql://localhost/test'
process.env.NUXT_PUBLIC_APP_KEYCLOAK_URL = 'https://keycloak.tech'
process.env.NUXT_PUBLIC_APP_KEYCLOAK_REALM = 'RealmName'
process.env.NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID = 'RealmId'
process.env.NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET = 'ClientSecret'
