config:
    sensitive:
        NUXT_PUBLIC_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:7TwPL+6L9rjw/YPDI2V0Nisknc3X+i+aylmq1JM6bONl7X/53x4akg==,iv:RYBef5MpOgS//OYTlLMY0urgUHF/dCFyRpUswWpVamA=,tag:29bDELCJiqeLPHqsTENllA==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:HzoFxKueJUZnfvoDr8o5o7m+KlfPrrzYNMF0LjL7qlw=,iv:DPkRKB3t49CHjPxY9k+brDlOqitSoi97aO1ZHaH/41k=,tag:FjldbeNCmAZkXS/x0s+7oQ==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:ruHJD8xePRoR77M0Up1YLHNxppm6l8c/ow==,iv:I1wr9eUNvUf9mD8Q4kfv3J+8Tsae6tFohkGPexp+M7c=,tag:deVqIVPDLGBDx4WrP0NxNw==,type:str]
        NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:20i1pJc/OuehjIf8Qld2cAJAXQ18r1kBOMMdvvulGTA=,iv:PNt4x3TG7u8Zo/Mnl2xq+W7hb5HGA9PaaK8Wjm6woWk=,tag:t2LYQLotHoS2rV8PrrLU7w==,type:str]
        NUXT_PUBLIC_APP_SENTRY_DSN: ENC[AES256_GCM,data:hFhqSpjGaWWV5UHK+/RiaAM+RgVWRSox5jyOC2ZBkwexIAFMreZz6NheVlN+ORKznIGXU1ULZM6nAg0zy2V/tDU=,iv:HbShxC0iwtEqEZ34/5UyS/j5iDn6IL1tjZ7xrr3mBcY=,tag:b2H5NbDf+THrI78tdIBd6w==,type:str]
        NUXT_APP_GEOCODING_API_KEY: ENC[AES256_GCM,data:H02XSJtBgYvVJNYtkGKz34qRRA2wgHnPnsKOhDQUG2cArDgCNgrc,iv:rzUEWFjEkwqOimRchLVZbFWNpuB2YbmUVPlt1tlQyAI=,tag:GqPDSzGSRliTOo9xVTVoWQ==,type:str]
        NUXT_APP_OPENAI_API_KEY: ENC[AES256_GCM,data:sSrmO7c3mWMdAuX9YCdj5y1J3txQ8H3rbZdRDYLcJadJXIOvlKh6UMqx3qEHxrmh/vSGBS7aVlEsLC9RFmE+qA3q3KQkbIjFgIktjUbi0DHYj+5Ru8QxE3/lbS69ZLayj29yHdEMsUGozryG5e9VZV89GnPYkAwr7WFZts2yd1o3BJjZi1FDnfnUFdJMo4mUnMCzfa+6N1mxsg9U6e9fgY+1uKk=,iv:d4XZrBFeqHvTmAevFpeHoYmNOEoZ6On97R1gTxIhkSg=,tag:XDp0LXcRl0ymm8yZEIYz8g==,type:str]
        NUXT_APP_SORBOBOT_API_TOKEN: ENC[AES256_GCM,data:T4nE4tTKo/IkAFdqG8neoNMbLJJnISR2FDt5kvPDYDpIslSFVLAWKlaTdTdy9J82q3uSGBJFTA6iPOSfH5Ht7rPv5ZFM7AZX4/pr/eM8tr4M8I6KMVmyZpwLs7vOq5jkG+eEt2L4AGbMO45sN3uvA9wQrMRfTcU7STOQ99djSDtFEZwK8bCNi4jic6OSYhcV3QP7R4gP123dQdSTrjSHPR/CA5PmQZ48YpFSjBJxR6KCwqiHsdiGUoDSnee7OcC1vsNm2k5s1+DGrjTcqHZjItAa6jFcPFUlkKHrS19F3U/rTqOLvH+gWRKFkHPgROF0o6ElVoG/QDTNW7F+x0WP52MMeh7hzhpyoa5dmsrWoM6IE+qnuYv0c5LJYnL+R+MYOu2z+r60z5xGHTGzyPCP/WZYjX7cdF6TOIRNYUZhzs8AaKFAQWSJaSghqmclGr35MMQ37ac8iN0bfmS1lRO/ucjIZPJGtMb6EZ8gJKh64a0tbhHJ0wZdY8ueNHbvJzONoDrcTP/SL7kmiSiDB4fK91+T5CunnkIUqzUIYAMROp+sBqcG8+da5CpdonK6K7Rm8jdhkg==,iv:ZZatTRyZtkUzW4UmyjJe5PVV+1xrRVkX+z0ZxG2l2oc=,tag:VJQCoogxNcHCGjmwveNl4g==,type:str]
        NUXT_APP_LANGCHAIN_MODEL_API_KEY: ENC[AES256_GCM,data:zD84DSoGIjdunPa8Cpc/EQHL1uCh8YltgBL4ad4QrNlqWG+fIOAD5QdMwebEzJWlZOirAJfvbkBSXh9CpSybwKCM/8j9lzzQVElwguWVYkI85sP8YI5DF2jy5NfqEtkwZ+6RiMhCftOSzzlH4Smjc88FpzC0rLW0oqutUjnmvco7/FwrMlk7XOva9ayerQe9nLHt1M0PZ9XWPM3Yz2yfWHVuzBI=,iv:RgvdcmW4bBd87rvFTaxgsWILAslTbQWH/Djb+UBlJ70=,tag:NX8oG8YPzta1NW2ERn11IQ==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_API_KEY: ENC[AES256_GCM,data:nSAjTM92yyHFV0qEFBpqsBjoPHjR3+BvyLuCv+atXE4K8KPpaAvE+TAvFTRJEd06izx7o7CK5yf7PNQYsGfVc99ay+lLJx8QqrKN8DmvTX0p1Gar0Fc019hstn0DOjiuzH31GzirlP1zNEx3N/mwFRRUIm1sC+jzi2wmV2iG8r7lvTy1pU4BIT+EkGyzoLKvQ+dzZBQFsDxMXBiX3lwF/U5KDvM=,iv:yI9iTcJGIHYoJITwNpL5anry06Nblv1wa0tfRnE5Kus=,tag:54mUHuoRWGyGGZZPDWs7LA==,type:str]
        NUXT_APP_VECTOR_DB_URL: ENC[AES256_GCM,data:hbSNA4n86/2ctSQENRGHNl1SIFNgFgYJqbYFq8BXYMpTYx9kEDeR0m7IGQajACAHrcqsKkh8aClygYIwX/vUHwP62DWJEfZyFxY9ao1XWEIbUTrAm9mFhdVwzBlki6fuZ/MAA+60Q/iOl2oyRDiQtsrFz6xPkljv71CQES6jdITFyuoQPCjiegLu6Z1h87sgkaWwo3T3RX6HokDQXOsmxUmZATzEzETSIUSHA15NNo7worLgvWfE,iv:VwWfBDYgAG/RcWBhvZYN0pXtLdc5SUdMgZFu3NpoLpk=,tag:S2Gb7WrCbmRcvMXotqfjcg==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_MODEL: ENC[AES256_GCM,data:qW2vXi18kS1gk53iL0T5u2YT+wGpaA==,iv:OXGWgk2OJrAcPb5jK6v04noaZAmNbyDqF5KCaBb0iBU=,tag:YhTC5r2su3tWZrpKh8P3NA==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_DIMENSIONS: ENC[AES256_GCM,data:lVo7YQ==,iv:V12Pf4U1vCK51hfBmS+s3osybFbSz2xVnP+PNb0hMZM=,tag:79p3u4/NbooOIw/TlmP91g==,type:str]
        NUXT_APP_VECTOR_TOOL_PROMPT: ENC[AES256_GCM,data:DCNPul9o5asQHxoKG4ZE1DEECqs=,iv:zZNMPuYb7B5k+CI0668YKAoSJOT7qv8E37oSxeeCw8U=,tag:l3yvaIoMCTHV33UJTsWU2A==,type:str]
        NUXT_APP_VECTOR_TABLE_NAME: ENC[AES256_GCM,data:VRy1AMaO1F3sAXHY/Jybwnoo5Cn8Dk/9ej1/UVk=,iv:syhVmlN/Q8E8pa481MtaJ1Kkc2Hji5Abi+/4eV3zTRw=,tag:3NUOqP7fUYH8CCkKkKPh6Q==,type:str]
        NUXT_APP_CHATBOT_PROMPT_DB: ENC[AES256_GCM,data:+7qrSaZYs2twUonC9Qm2lj0O1/zhUFBT+2fQYQJ3HuS2m+TojUMahwwdxb4xL3ykSpxy6PxdXGcZyeYam0qEYTHmL0TlSqKBHzw2DTluLXUHAzPfSJydUuYp6INzhIyf2zpOf9GHeANMfVv3Y25Hj282P5ACrBAJ4lNbVmMFGgIMhy9i97fJ4fe882Tf9y+TCtQYKayHYInXB5YmMLHDRxi1Dm/DdmDNX4DT,iv:GfYzs2BCIcsvdENmwqwmVp+16leoS2EK65WFdy+e9QM=,tag:SocAWzWw0qX4gZ2ogB9LIw==,type:str]
        LANGSMITH_ENDPOINT: ENC[AES256_GCM,data:qtIyIXhfMcV95xFMwXV9L0FAxs/WPHrq8uUWfPLoZUkoKw==,iv:dAkp8L+P20MkQByR0UbKFfFiVeT9SKMQIXPnTR39YZ4=,tag:hpshStANd+HC1OEP867T2A==,type:str]
        LANGSMITH_API_KEY: ENC[AES256_GCM,data:KW5LxtM0Ubcoau4GsA8Ahg3H5cFOXzd1jyKjSX8hp51MB+M6WPraX4YAtO6UU9ZKDr5L,iv:kyhhWotxMzg1bJ+FGXHdroLIThhZir4KN0fQ+Q8NsHI=,tag:KnL0ztx6sxOd7o56QR8XEw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSTdDTWdqUjAxVDUvQXcx
            U1MwSm5sNkFlb0NJMDFXc2NrVGpIUlV1SmxnCnljK25nVHpXdFlhWVp3aEFXbWVL
            V3ZzbTJpTEViWTl0UTdzYjlVb3FNZm8KLS0tIDVETnhsdWlqUjFEajhYTjlSQnYv
            WlhuaHlVOFR3aHFNdjVqSWpyb3hrUEEKQ5INoHL30zaLVjq9f64NEP0zQ23pZcgf
            8iFiERGG+LssiNc3Br6y3Fcg0c3E60NrfGnke93CTHiavKIxW+yANw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR21zanNLU25VYzRDb0VO
            cGVOZDEwL1krOE5HOUVxbk5BZ3UyVDM0ZGg0CkNSZkxKMm9STE1jOHNhd1hGc0NE
            RjFZc1Q4YVhEc1RES3dvb2lIR1NkSEEKLS0tIFNEQktaUUFvM2ZvZ3BkWkRZU1Zl
            ZWc4WmJtUUY4dktTQmp4M2R2dWUwV1EKLtmcn8oAxaKNv5xlkzjuKY1DXDTCC+xA
            ErrgKIS7MjaptmY0RXH6qDv2A/yTQUiW91pKLur0TFSukclfJdlJuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNFB5TUtxdWR3M3IzSUFI
            Yk1iQ2l6M2VOSk9UUVNPc0lWU1NzcjQ0bjNzCm42dEVGYzI5Tko0V01nVmYvV1Rx
            ZnRaTnBUaDA4bVBOSVZTTm13YjA2bXcKLS0tIEwvWGswZWprTkVGbnRRMjh6Tklz
            QmRMUW5vU0xPSDE1ZmdwVUszKzhDZ2cKxU4NSSBI63FRQDTeBpkG/qnQ4nNZrfeD
            flsmd2xKdCWgGD5+puYxl2TVA1pGDrwT8SxBPDroyvg3teUelIQ3OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWDQ0Z3MxTUloc0ZsdXRD
            WjkwU2dxbm04bjNjV0tUSitUTldTUHhkU0dnCndSMFNyMWV2c2pqYW9OWTJSdXJw
            eDYySzZSWHR6WHNEYXh0eVAyaVF2RWsKLS0tIEJwRWV2OGhGZFExSmNHV2FWcWF3
            cGRUTTlKQTZ1b1A3SW5xNG0yVkRvYkkKcSaUqrHO4G5nY9uIfRUEP5kkGUu+BPp5
            hvSwVTO7fsUeRzoFHv5MCuEgPD1gXoxKWXQDZyPVvyiW89ED8dfyJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteHhLSmtFc3pRV2RmYkRa
            U1M0RTV5cUIrVUFZd0pITkx4SWphVEVBZGpFClVtYkZJemNtbDBKbWhwSlFjOWhT
            aTFZQVMwRjd6V3ZLUkhVdDVoN20xQ1EKLS0tIDBHMXZKaWhaSUZ1S1U1YmY3TmRT
            YzJTZ2Y4ZmlJMzZlZ0Y1eS9qNElOL1kKzx7zuqTJPnz500TPNgzPkF1DcQ2uA4l7
            wxQkHW9p6yhwv6WIILTgOZRt9uvj3HmyTJnXsgINEKh0OEhEMburZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV204YThCdE1MN3QvR1lU
            enFkNFF2dTBJYkVRN0lpZS9kYlc5YllMY1ZZClFwNEFwSnMxL3ZSdGd5OHM1dkVI
            ZVoxMzdpNjNTOVpwa2dTUDErU1oyWGMKLS0tIDJLZ0lsbXlxSmFMUEtvTUp5MFhl
            WTVMdUd0aEhYQm9tZVhYQnN5Lzd5N28KtgXBxBECWeVW28vKgEYO0t+3b4iEX6Cs
            8zVe2y5mlHrkf6fWBlbw2LdHRR9Z+HhyH/k8PQc98tNmOsBa6mygUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T10:12:39Z"
    mac: ENC[AES256_GCM,data:6lyDxE5pIVzWUTA/ouluKOOmDkW6L+OhEB4sMnQ1sIQr3vCPaGTkqpgO3Nc0NxhNekL+JkGqPmMaxoad4PlYqJOstuUSrlzKLuDCtMxZe5jnu91dpRnCfDBK7S0crQQJhmGzKbyKZDz3NLl3Iig/yym8FjFthXqTKPOjNnR32jA=,iv:quolIrpr626nLRfHTTyKi1ZUMpQy8Rb3nDD35UYH5Mw=,tag:5MueDsezAmZC+xn3npannw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
