config:
    sensitive:
        NUXT_PUBLIC_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:EJ8PD6Bb+nUN3vx0gz21I5PNEeasKOm17WDOdNkCgwZ3s9hoOTTj+Q==,iv:RKjAnkRULI4iZJYH52bcz97sFc6CvIkQ1a+aR7sd+Q0=,tag:rRF548v5xyw9NaBNi9kXmw==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cuDLLmQo92fIX/VrvE67XSP3zusJfI6AUH1eG3t7An4=,iv:M6mAZPVtPEGTK2Q+F1l5Q2qfe0y1JkJiaaDUaMSLACg=,tag:CuVd1Yf6ZMsVu934nrvWhA==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:JOCTHKo1GqTipwQBn6Otjs5lHI5c,iv:wugi0qMqsOXq0BSbGM0qFZ6JgscUVPKOTUMWwQxkMm0=,tag:THLLP608/WDdAvOETkmYOA==,type:str]
        NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:T2uUOflyvcwxElnl6BwcK0CANYgrDfg3cFP1cwZxeIY=,iv:QjsK3106A3pAkKi9zTH7yFw9Sb02XoU93XqNclJ5s0g=,tag:myQ/K1i0USGlbXjwTiMuMQ==,type:str]
        NUXT_PUBLIC_APP_SENTRY_DSN: ENC[AES256_GCM,data:m1Tzz7jdqKGeUseyfh8SvMfpNX674XY0R1yrP+fgBipt4uUVdpywb/nIo0AoTVmxt0u7JO0+Lux7fXy5VVAsHDk=,iv:pb2mCOmgveNL3NH5VyVhaHOaZmH1QlP00nvbQMDEXqg=,tag:tDTkOFhfVexnkmdmr7ez0w==,type:str]
        NUXT_APP_GEOCODING_API_KEY: ENC[AES256_GCM,data:ygj1xkfUpNwzxUorVC+eHLXfgzL87Hh0LLlIaiuPl/8/OYR8dVdD,iv:al6lr3IzxzBPAj6DPLiYj539V+K9FIuAguGsX74ewmc=,tag:RJLyJ4bLcBucKftodxXTgw==,type:str]
        NUXT_APP_OPENAI_API_KEY: ENC[AES256_GCM,data:p1rqidtGJFRlVcYWbTEaZBe6EnTRmxLTgX8PFKC4l8KGPL0VnoKOLL+yNqumgSqlNyONGs6x0RFEY9InRWylcRm57X1QhCwE2X/n2P6W1uzE1pK0hFxcrOwF8vB/0W+wB4qwbQgXvXM/68/dM1c/wCrmSk0er1iWqR/oIG5C+u5w8TDNkKmz/TDs5KgrDDoj+4KC9uRb+VsoX77ho4lrRXmp/bY=,iv:tTX+OmuDkTAfNxZOukA4vvSpb0mvxwzmNlFmD9OSN8Y=,tag:AfQ0gPJqPlLOIkLtu4hDyQ==,type:str]
        NUXT_APP_SORBOBOT_API_TOKEN: ENC[AES256_GCM,data:ZAnA6WOEBZBSsh1t8bLHtL6qXnUscz/kwhSOMJyeKPvOsT0tV5D8TRF/aRqNRTOiQaHUI7FN/mmIh5LicZrur5Tr0/Q4LghnR2FnWa8J3UH5PkbrFZPeeh4DHtgTcN9j+1f3hCGgHWe7cNy9rBJIX/HUGBs6uNE6Lv4Nf4riLfCJldOUk4pYESu4TwCcaExXNwuKkXsciXkAVG2b2qMLo0eWZ68jGz4CevtR5WkbCjKH9JkyOhlrJdJTrUFLgTpYNmxT9HLAWMk51PqiFHTrI1aOdCKwxx3btYIbtQAasYm6n+p+54u2V46GNfzRWwwaDVEYYYVDO1rNi1vHEv2IIO7PPmFJO0biuAB7tWvlOPlI/9KdVv7H7BhWB7ziscDUaLVzbMI66yIHeBdYIvcJTG3qQ1opqlkLajEh7YhtT0USejNHj8+c3brZCKsjEk5Clbk4br5bUAkkOndwYS8PtbHi6GuRrCsvDNGaH+EEmztF1ljhfVMn2S4N3xzkxCpKapQTzPIG0GzmhTEBjeBKOLioizAfKXG/phdtyrHjNeqRjINcFmJekJJEzink1SVNe9PTHw==,iv:2H7uHSVC5Ke13NXazCHxLsi/GlAVdvlVkVFEfTC84SI=,tag:zrNgDnPbd07uPDtZJsvD8g==,type:str]
        NUXT_APP_LANGCHAIN_MODEL_API_KEY: ENC[AES256_GCM,data:dDMYGHqONYhEeM7zVf80IjN1BeDtDv63vlAYGLlRC1uAnGX9Usezp4qGFVEIZNyiDenskfRrVtn8ijpd5g4SBWR9k4M7nwYA+R4AxZZzsbDhQllafcL+Zz0ytH7xfEL+IWbvSUJdXt6ek17TDcSFqqorJmqFyXzKu4KadzL+KNUzAwN1JUuSIp7rAnUROVQ09z1JxDkjP4R86UzmpL7xrcjQut4=,iv:OD3MWt3rU/2JM5bYwktRApQaN8zsYBFXXxs2XzxT6T0=,tag:C2e/jfDV6PXSCeiHevV3HA==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_API_KEY: ENC[AES256_GCM,data:mICOh+ebNTSiYFnPo8viVSikYRsAp1kSJ1heY+eBGLZAYCfF+hNM5YCTCOwWyBMuDrusof6Nkr7HC7FFZ9OiH5kTz644vMw7JYnl+Ss+2JIP17TmnuwytzJ61e3TwrHSHPK0GZu02qVHBX0/sKZ9kU4Ab7jxA+QPULCbpAVS5bJy2Ucr1LrGjrEcVnq/eJ1dZe45ag23ObvAtA6XEkH+Qy35yO0=,iv:sp8HZI2y52qz1yVgsTosPpSpQEgX7fdb20ZGwtjB/ps=,tag:kqHvOsG0LrejPwYZFKcG3Q==,type:str]
        NUXT_APP_VECTOR_DB_URL: ENC[AES256_GCM,data:G2zzg9nyutTq69jgAaHXMQJCwVnfiLP8veI/I4RQ1GhF6jpESuW3yKY9F3vOiN2FU0cTYFYGUMAd7cLDv2f3aCrtTEcbhzl+kaW1lSroH4MPzjGznkaq3oSdMaLZawvd3/3uZl3cXzpKo6fJHcptTTnMGnqfKrWxoVIMHPf0PX80CSC/Ibx638+ip/iDfyeVazaZAHxlAJ8FTvdHnxsHUzO3GjUOoqUb+A==,iv:JrLN/defJlm9TtmiyUEE6mRaS7Ci9BTuHlPTv3f29LM=,tag:GaxlfngPBkly97dAUQ9K4g==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_MODEL: ENC[AES256_GCM,data:6QVSvIJcfL4UEykludmzPpb3fpQUew==,iv:yPAHjDOIMWW8WIs0M934xFPr0j2c/C+JmgcheNbVNMo=,tag:lo1T0jGqXSCRgw4YSU+UgQ==,type:str]
        NUXT_APP_VECTOR_EMBEDDING_DIMENSIONS: ENC[AES256_GCM,data:t4SHvQ==,iv:U1Ck/CdtMrkiz5tUKbrYAmTeF1h0ghqZgbFgTYYajgA=,tag:XcEAOFYYnBGaqIkZjHnbPQ==,type:str]
        NUXT_APP_VECTOR_TOOL_PROMPT: ENC[AES256_GCM,data:TsGjwPSqP/tIgj6oKHG7ufG0q0Q=,iv:8QCEusZVCUiJy3R/PaWw1WEsv+J9V21/gnGEO+Ob9So=,tag:pJVlAR/xOE6E1D1AdLmBbw==,type:str]
        NUXT_APP_VECTOR_TABLE_NAME: ENC[AES256_GCM,data:AvBnmwfWbwoqzxkI8XN4zTeOM0Be0taHLlStKlgQjBOu,iv:e18Lz8epyH0yym+hS9IUOu6yRLMlapfyIor0F8Ipaec=,tag:hDxGQIM4NYMzxBxgkvEurA==,type:str]
        NUXT_APP_CHATBOT_PROMPT_DB: ENC[AES256_GCM,data:d8f0AH3px8XODQlDseqNWCPb/B/xVkWaPqKP/8/DXfCluYXuFqNH1vGi200O9/HxPYRKXScwPjEDQFOzlROPWIrpSRaFo+lYPqxHmx3N2fa0UtFdAisz+xKrzHZrKfnxEgo53uARkeKB0rU0OuU4TBYK8GFk0clesPhAXQ+0RjelldU0V8ylf0pe3Jn1KrBuLo13KrzyS0/na9w=,iv:1gyZ7lRtMksaZqpxVKxSJxY+Ay7F/22XI+qKvbTakik=,tag:tipbXLd7oLT/1VO9ltqNmA==,type:str]
        LANGSMITH_ENDPOINT: ENC[AES256_GCM,data:gfghYyHd7cSoMH49Htgf+8QsQyMcrxRjFUujRt9q6xuGXg==,iv:ufLAHX19mT59zljjYOs2CzjjxPWHQS5xJw1jJqi3hQY=,tag:PgByiy2V0DT/canWw4rcoA==,type:str]
        LANGSMITH_API_KEY: ENC[AES256_GCM,data:qooj4kGWd4hDlBcRVkGfPT9T0t5jJMbXOjcNtnIIfYXW7Kiv4W9BiCYoqrzPazOY9dWF,iv:K5h60KXlcNCH9JdeEy9CAqmOPumhLn6idC8dS/4bQTU=,tag:TfKVvLpdJYUhSoFW1iWQ3A==,type:str]
        NUXT_APP_MCP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:F7XySKsufW7hLdSQwrXgfez3u5CRjiEl,iv:fsq7NjUUi/NNOApgsUJu5B5xm7prFGIg1o9YC5gkWD8=,tag:GvzwK1+2o85phVEbwhp01w==,type:str]
        NUXT_APP_MCP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:AQrQdFC1zxCk7/JsYdMQdlTTKKi1vozsOm9wChXTO31WDDAxNdofJYGLZpO562D1GaCXYTOF/UliIO9Pp1XHM0P9YoRNuf4hvLkJy27I/Y/qBQQUqbM=,iv:nLYuEnG/PXQygZolHMaoCWEw0BMmxHjF9KDj1IWzoko=,tag:d7shs68kCveWJuOdQnOy7Q==,type:str]
e2eEnv:
    sensitive:
        USER_ADMIN_PASSWORD: ENC[AES256_GCM,data:RXWsMLtLB8v5YSWB,iv:tK9wwRpTuXdSFy5jyjk5aQvXAI58MZiu+aqVXHiz+3Q=,tag:LWyz8EF5wivXiw7BnWz+Fg==,type:str]
        PLAYWRIGHT_TEST_PASSWORD: ENC[AES256_GCM,data:GjkRgTf5NKp6iJy6,iv:cVhuJZRbTnny6IH9gMLQCAnkY1F8ajOUlu/jU238YkA=,tag:qSvPNo88SauKUfzBa4R/tw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV1RFL2NaTWhtZVcyYnQr
            UEllQ244Q2tITng2dDN1c1VUQStOajMraG1RCkNIU1FKaVFJK0ZqRGlmcmZpZThk
            L0hmcVlzREpMNDU2WU12RHhyV2QrcXMKLS0tIHQ1S0owVkdyNlVNMUVOeGk3dTk3
            UjlQQk1TVkRiL3FDejFYUzBVenU1a1EKW6SJqli+FruTBXYZj4UeSryy08fACS3n
            l3HOLcV9UdD3b46Ie8dQaFucTwba1qDbhk0/5Nz/XHxgMs+OgK2Kdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U2NWVzMycS9QOG9pc1ND
            b2hxTFYrVmh3OXJubzltN0lPSHBTT2p4UHdvCmVrbUdsTm5ldWYwZkZESXFydUpJ
            WlRrNGo5SmVacVdhRGI3NE9NLy9iRTAKLS0tIHFPNFE0aFVFUFEwbkRpdFFVS3Ja
            VjFxNHNTcUl3aVhXZXRXdUlabTlZK0UK+JULh0RFuAM+9jCVI9F+l9t/M8rKP2Jz
            fU5tfrepAgOFqgHGRh3/aPdGoL11YlU77mZU4yCJ37Ns6Rb32kvO0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY3hKek91c2YvYWlzSUhr
            RVJWRVJRRGN4TzdEelBJbENXdGl0cXJBa2p3CjNGdjJvYTJiVjB3WVFhRTUraEIx
            UVc0eW5DZHR6NXFNN0hldnp0TWptaWsKLS0tIFZreWNQUjYrS01PQTI3RFpyb0wv
            SWV2ZGpXalhyVFNCVXViRjhCQ3cydkkKjqRkYl4o03WFBlJlPZtz2LYZgB8KrlPh
            iMFnXEiej/5EyZu/vS5XzYu7mItoMHNJdvg5G3KkGsj+a4cdEDf5/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNEI2S01KTk1nT1BIdGVE
            RjhEaHRLeTFadGUxY3NzNTJMWDgvcElFQlJNCndzcXRhM2VvemdFenRiQks4MElm
            bmNQejdiWTJsTGdmajMxNkxJcFg5NjQKLS0tIEgyRnRDOGFqQ3l2a2hkdkQ1Zlhj
            eVAxZnlHQ0t0VHlZd2orOUkxcEk4eUkKXYBNSyO1p75tb8YezaHspD52OH1Qo+CU
            wcxC36bjECkChY69+DrQHpsguYG6+n1QURptlLr7dNzom0ozh0+nfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ2wrUUtYRU1XOE9tUk1p
            SE9XZTUvZWY2N0NETlZ1UXhBcExzUHdaRjJZCnJ2T0tObklueXBveFZrWWZhb2p6
            SDUxUGxOWDZDTXhqUE1IUklGcmJRZVkKLS0tIDlhS05aVTNXRkF1bUw4VWZUbWU3
            cnVjNlFpTnE3Ly90c05mb3pDUGZCM3cKR+ARBl9XLl4wt6I73GABWkOLsqnvs4QT
            2v1dB/s9cm4yMkjQiYmVbWbjDOOhda88Ut/5Xiq2YHPFuVegLa8TVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOUw4UzJSdmNqb3g1dlBI
            UXZSUHYzd3pwQTIreDZGOTFvQUtWaWNBbWhFCmNzVVZLeXZnOEpSSHdTYU5seHl5
            UjlLZGZnNU42Q1JhcTl6bldzVlJONEkKLS0tIDAzaFhjUHBrVHAwS1l0N3NUN3JK
            UjJXY1BMYjRzQ1kxNW5QSTBVRWt5UE0K7zntVA9ii+mkTXuKNzRcsTEZInJpBBZD
            mWZdyM4u6Sl1YH6rBWbmncEuiOAjH6TpH1A+Ap3l5eOmIgDwP1Ti2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaXlkOUtaZDgwbjZxUEVI
            bU1Da01pN04ySkVQTzB6RUtaNGkxbzFyWHhBCjlGSkJEc3EvbkptbXBxWVFab2Zm
            LzdkZ1Rjdi9NWkpQcnNyTzh4aWQ4bFUKLS0tIGU3WnFvalFLR2Y3L0ZmQno2d0xu
            RzNiMEZMK1FKUUkrZnBrQks0T24xMTQKmtRTd/JNinFVCUr8ZHAb5pxvuXKe4fZc
            6G8q+m7BuTcuIKcYc0YatdR9Jsd31J7koxXfCh8LJfdATK09NpiEHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T14:50:48Z"
    mac: ENC[AES256_GCM,data:FofIzEu+JvOz+HNQRYOCrV5cKj/m9cA0fcafE2NNlzpC+FoYTJWqZjtcml2O5vOX61fM6KfGxnOc1g0OZ+PwufHmglCzl1a1dITPpdZzBzWvncM2VQ5nT6OZ20WahzF6s23mOqKP9CkDG6k0PMn2scFcg7NcJrOzQlmfZX71RWE=,iv:qD6LEZiAP4lB9ZE91MHVo+2rlcISVI5NDnw4+CG37sY=,tag:1cDmVWMunRcBOsop86SEQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
