targetPort: 3000

commonLabels:
  app.kubernetes.io/name: projects-frontend
  app.kubernetes.io/component: frontend
  app.kubernetes.io/instance: "{{ .Values.instanceName }}"
  app.kubernetes.io/part-of: projects
  app.kubernetes.io/managed-by: helm
  app.kubernetes.io/version: "{{ .Chart.AppVersion }}"

image:
  repository: criprodprod.azurecr.io
  path: projects-front
  tag: "{{ .Values.application.revision }}"

resourceName: frontend
fullName: '{{ join "-" (list .Values.instanceName .Values.resourceName) }}'

config:
  nonSensitive:
    NUXT_PUBLIC_APP_API_URL: '{{ printf "https://api.projects.%s" .Values.domain }}'
    NUXT_PUBLIC_APP_DOC: '{{ printf "https://docs.projects.%s" .Values.domain }}'
    NUXT_PUBLIC_APP_WSS_HOST: '{{ printf "wss://hocus-pocus.%s" .Values.domain }}'
    NUXT_PUBLIC_APP_META_PORTAL_URL: '{{ printf "https://projects.%s" .Values.domain }}'
    NUXT_PUBLIC_APP_MIXPANEL_API_URL: '{{ printf "https://mixpanel-proxy.%s" .Values.domain }}'
    NUXT_PUBLIC_APP_BASE_URL: "{{ .Values.hostname }}"
    NUXT_PUBLIC_APP_PUBLIC_BINARIES_PREFIX: https://criparisprodprodassets.blob.core.windows.net/assets/public
    NUXT_PUBLIC_APP_PROFILE_EXEMPLE_RESEARCHER_SLUG_OR_ID: ""
    NUXT_PUBLIC_APP_PROFILE_EXEMPLE_PROFESSIONAL_SLUG_OR_ID: ""
    NUXT_PUBLIC_APP_PROFILE_EXEMPLE_STUDENT_SLUG_OR_ID: ""
    NUXT_PUBLIC_APP_KEYCLOAK_REALM: lp
    NUXT_PUBLIC_APP_SENTRY_ENABLED: "true"
    NUXT_PUBLIC_APP_SENTRY_RELEASE: "{{ .Values.application.revision }}"
    NUXT_PUBLIC_APP_API_ORG_CODE: "{{ .Values.orgCode }}"
    NUXT_PUBLIC_APP_I18N_LOCALE: "{{ .Values.defaultLanguage }}"
e2eEnv:
  nonSensitive:
    USER_ADMIN_EMAIL: testautomatatiquedministrateur1@outlook.fr
    PLAYWRIGHT_TEST_EMAIL: playwright-test@outlook.com
    FRONTEND_URL: '{{ printf "https://%s/" .Values.hostname }}'
    CI: "true"

resources:
  requests:
    cpu: 1m
    memory: 15Mi
  limits:
    memory: 50Mi

backendServiceName: projects-backend

networkPolicy:
  additionalEgresses:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "{{ .Values.namespace }}"
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "{{ .Values.backendServiceName }}"
      ports:
        - port: 8000
          protocol: TCP

maintenance:
  enabled: false
  namespace: maintenance
  serviceName: maintenance
  portNumber: 80

workflowRbac:
  executorClusterRoleName: executor
  serviceAccountName: workflow

e2e:
  name: '{{ join "-" (list .Values.instanceName "e2e") }}'
  enabled: false
  schedule: 0 9,15 * * *
  timezone: Europe/Paris
  concurrencyPolicy: Forbid
  image:
    repository: criprodprod.azurecr.io
    path: projects-frontend-e2e
    tag: "{{ .Values.application.revision }}"
  commonLabels:
    app.kubernetes.io/name: projects-frontend
    app.kubernetes.io/component: e2e-tests
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/part-of: projects
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  blobName: playwright
  storageAccountName: criparisdevlabproje2e
  reportHost: projects-e2e.k8s.lp-i.dev
  notify:
    failure:
      enabled: true
      slackChannel: it-projects-frontend
    success:
      enabled: false
      slackChannel: it-projects-frontend
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1200m
      memory: 1.5Gi

sablier:
  enabled: false
  groupName: projects
  traefikMiddleware: "{{.Values.namespace}}-{{.Values.sablier.groupName}}-sablier@kubernetescrd"

ingressMiddlewares: []
