config:
  nonSensitive:
    NUXT_PUBLIC_APP_KEYCLOAK_URL: https://id.learningplanetinstitute.org
    NUXT_PUBLIC_APP_WSS_HOST: "wss://hocus-pocus.k8s.lp-i.org"
    NUXT_PUBLIC_APP_META_PORTAL_URL: https://projects.directory
    NUXT_PUBLIC_APP_MIXPANEL_API_URL: https://mixpanel-proxy.lp-i.org
    NUXT_PUBLIC_APP_VERSION: '{{ .Values.application.sourceTargetRevision | replace "_deploy" "" }}'
    NUXT_PUBLIC_APP_ENVIRONMENT: prod

certManagerClusterIssuer: letsencrypt-prod

domain: lp-i.org
