import { usePublicURL } from '~/composables/usePublic'

import { resultFromTool } from '~/mcp-server/projects/base'
import type { TypeMcpServer } from '~/interfaces/mcp'
import { SDGS } from '~/functs/constants'
import N from './zod-schema-utils'
import { z } from 'zod'

// generated by perplexity
export const ALL_SDGS = SDGS.map((sdg) => ({
  ...sdg,
  item_image: usePublicURL(`/sdgs/en/${sdg.id}.svg`),
  item_type: 'sdg',
}))

export const mapSDG = (s: any) => {
  return ALL_SDGS[s] || { id: s }
}

export const SDG_OUTPUT_SCHEMA = z.object({
  id: N.number().describe('The ID of the Sustainable Development Goal (SDG)'),
  title: N.string().describe('The title of the Sustainable Development Goal (SDG)'),
  description: N.string().describe('The description of the Sustainable Development Goal (SDG)'),
  item_image: N.string().describe('The image URL of the Sustainable Development Goal (SDG)'),
  item_type: N.literal('sdg').describe('The type of the item, always sdg'),
})

export default (server: TypeMcpServer) => {
  // Add an search tool
  server.registerTool(
    'all-sdgs',
    {
      title: 'LList of all SDGs Sustainable Development Goals',
      description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
      inputSchema: {},
      /*outputSchema: {
        results: N.array(SDG_OUTPUT_SCHEMA),
        },*/
    },

    resultFromTool(async () => {
      // only return sdgs
      return ALL_SDGS
    })
  )

  server.registerTool(
    'sdgById',
    {
      title: 'List of all SDGs Sustainable Development Goals',
      description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
      inputSchema: {
        sdgId: N.number().describe(
          'The ID of the Sustainable Development Goal (SDG) between 1 and 17'
        ),
      },
      /*outputSchema: { results: SDG_OUTPUT_SCHEMA },*/
    },

    resultFromTool(async ({ sdgId }, _) => {
      // only return sdgs
      return ALL_SDGS[sdgId] || 'SDG not found'
    })
  )
}
