import { z } from 'zod'
import N from './zod-schema-utils'

const runtimeConfig = useRuntimeConfig()

// generated by perplexity
export const ALL_SDGS = [
  { id: 1, title: 'No poverty', description: 'End poverty in all its forms everywhere.' },
  {
    id: 2,
    title: 'Zero hunger',
    description:
      'End hunger, achieve food security and improved nutrition and promote sustainable agriculture.',
  },
  {
    id: 3,
    title: 'Good health and well-being',
    description: 'Ensure healthy lives and promote well-being for all at all ages.',
  },
  {
    id: 4,
    title: 'Quality education',
    description:
      'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.',
  },
  {
    id: 5,
    title: 'Gender equality',
    description: 'Achieve gender equality and empower all women and girls.',
  },
  {
    id: 6,
    title: 'Clean water and sanitation',
    description: 'Ensure availability and sustainable management of water and sanitation for all.',
  },
  {
    id: 7,
    title: 'Affordable and clean energy',
    description: 'Ensure access to affordable, reliable, sustainable and modern energy for all.',
  },
  {
    id: 8,
    title: 'Decent work and economic growth',
    description:
      'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all.',
  },
  {
    id: 9,
    title: 'Industry, innovation and infrastructure',
    description:
      'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation.',
  },
  {
    id: 10,
    title: 'Reduced inequalities',
    description: 'Reduce inequality within and among countries.',
  },
  {
    id: 11,
    title: 'Sustainable cities and communities',
    description: 'Make cities and human settlements inclusive, safe, resilient and sustainable.',
  },
  {
    id: 12,
    title: 'Responsible consumption and production',
    description: 'Ensure sustainable consumption and production patterns.',
  },
  {
    id: 13,
    title: 'Climate action',
    description: 'Take urgent action to combat climate change and its impacts.',
  },
  {
    id: 14,
    title: 'Life below water',
    description:
      'Conserve and sustainably use the oceans, seas and marine resources for sustainable development.',
  },
  {
    id: 15,
    title: 'Life on land',
    description:
      'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss.',
  },
  {
    id: 16,
    title: 'Peace, justice and strong institutions',
    description:
      'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels.',
  },
  {
    id: 17,
    title: 'Partnerships for the goals',
    description:
      'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development.',
  },
].map((sdg) => ({
  ...sdg,
  item_image: `${runtimeConfig.public.appPublicBinariesPrefix}/sdgs/en/${sdg.id}.svg`,
  item_type: 'sdg',
}))

export const mapSDG = (s: any) => {
  return ALL_SDGS[s] || { id: s }
}

export const SDG_OUTPUT_SCHEMA = z.object({
  id: N.number().describe('The ID of the Sustainable Development Goal (SDG)'),
  title: N.string().describe('The title of the Sustainable Development Goal (SDG)'),
  description: N.string().describe('The description of the Sustainable Development Goal (SDG)'),
  item_image: N.string().describe('The image URL of the Sustainable Development Goal (SDG)'),
  item_type: N.literal('sdg').describe('The type of the item, always sdg'),
})

export default (server) => {
  // Add an search tool
  server.registerTool(
    'all-sdgs',
    {
      title: 'LList of all SDGs Sustainable Development Goals',
      description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
      inputSchema: {},
      outputSchema: {
        results: N.array(SDG_OUTPUT_SCHEMA),
      },
    },
    async function () {
      console.log('foo')
      const output = { results: ALL_SDGS }
      // console.log('MCP TOOL CALLED: search', { query, output })
      return {
        content: [{ type: 'text', text: JSON.stringify(output) }],
        structuredContent: output,
      }
    }
  )

  server.registerTool(
    'sdgById',
    {
      title: 'List of all SDGs Sustainable Development Goals',
      description: 'Get name, description and id of all SDGs Sustainable Development Goals.',
      inputSchema: {
        sdgId: N.number().describe(
          'The ID of the Sustainable Development Goal (SDG) between 1 and 17'
        ),
      },
      outputSchema: { results: SDG_OUTPUT_SCHEMA },
    },
    async ({ sdgId }) => {
      let results: any = {}
      try {
        results = ALL_SDGS[sdgId] || 'SDG not found'
      } catch (error) {
        console.error('Error fetching search results:', error)
      }
      const output = results
      // console.log('MCP TOOL CALLED: search', { query, output })
      return {
        content: [{ type: 'text', text: JSON.stringify(output) }],
        structuredContent: output,
      }
    }
  )
}
