injectedEnv:
    sensitive:
        VITE_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:o15J3P326/oT6lrqlSaFw/k3KgiBO8uJ2J4Rzpg5CZq50wmqThY/zQ==,iv:UQeX13WcA9qciYIf5dtdcCtX5MrtXZ/6SfPaEYvWjOk=,tag:15KpNYulZ8GP0GngoX+oKA==,type:str]
        VITE_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:x/SPpKqQM8nqxkPnSdp6cOF3+uUJ7gIhAxlwRgR+RV1I+ojJ,iv:z6/Q1RMiFijomuxMkt1znsqJoR6bcRCaGiiqnQEsaCQ=,tag:XbSt9tsAmZkfwWRoyu3AtQ==,type:str]
        VITE_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:0b07S269P4SmyAXL+UmHQCqaojdc9jHRQxM9iQ==,iv:ic1TGVxMAgO2IF/IKWrb25+N99qZ7e5oHIFWS5nTIHE=,tag:Za4i9bco4vXlfRLS1QiN0A==,type:str]
        VITE_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:WiSTd+LL/lr80svnPl2Be0KQhF9u6HwfMRNClbOyPKA=,iv:c++/0IKw35Ckc8qhgtnJUnP433FQwXx0x5bRWvS4w3s=,tag:xM14kgK/QwAoCoXOUwB6Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSys4Q2M3L2dyNUFYNXpQ
            emtSemFpU2FFQnNucmFFdkQzMHgyUy9xbFZZCm16UnZkR05sVXJGUVdkZWJCY05w
            OW52RS9TMTRlS0lIeUQ5ckhpN2FCUkEKLS0tIG5IbksxUUVMVWxaWmp3Y0FYbTRU
            OTYvZXBkVW9UVm9qVEdDZE5od0l6cWMKb/dgPRVo87G/vUlM5gQTJDaBz1uW/lwL
            11FXEhNpLHX+sMlGNGEvcbPYxRt/bz4G0BYA0smMWJmJvu4/lHMwgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x3t3s6e7hslylj6p37tt24mm5lj53ngeekrgphm5lfryg3qjpscs3l5g40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc3V0Tktjak9IdWNjbzRl
            RWNZMWhLeExJaVo3SDg2OTh4T050cSs5WnlZCkVNQ1Q0ZnRqVFA1Uk1wUnJLTXNr
            dDc1bDdHSVFoTGFyKzc5Z1ZiQ0dVek0KLS0tIHJXTHZaajVlelk3TVNXNmpkdU14
            TnZiUnlnUE1PRnB3b3UrMmtmeVl6N1kKivId4yfHBwLI88gghWnbQ+a+gKrcNeb6
            geaz/d6PhJkIxdY+fA023JilnklB3+rWLZEcKamcomLXTrCtU7xq7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yc3dc5322xx03sx2xy5n8w95fzfrc46qcgj6c8hcfes2288cgdvsq0wapf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuenlsVjV5Y01QVzlFT2VW
            TW1UUFE0NWh4SmtKVUlkc1NlQzUxQjNpVW5zCjYrb1RaL1lTT3phQUFuTHpzMVov
            ZWZrZS8yNTlrbkYwUHJNRTJFYUJWcjQKLS0tIFkzUXY0cGNzWnZPTFNGOUoxMFMr
            Q2daUGlwT3k2RlEwTUVCWUNHQTVQYlkKUSFl4u9+h8nQTSgcqOUgQJR5cRLnKvES
            7MCvkI/526ES5K86IhjBnLv56clImaJ4Pxdwjgp875X2qNJhM60k6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZjBYcXB6d0RtVm9DUXpU
            Y0hPU25kaG9nd1JOVkNVdFJleDlLNEtlS0RBCkdyRytsM3hTWEwrRjV3R2pINjJw
            eTU3NHQySVRsakJxdWhzdEFXWmFDR2cKLS0tIC8rZ2MyZ1lyYXdPODdPa0VDSnRh
            anBQai9wWm5kOXNKYTc1aUlOTSt4THMKQGZga2Cwoco6tYku924SqtaJZ4U0cWbK
            0ixvr3JsVPQ2WuitnLLfvXyfGpsRf8unEI8WKHqD63ZKD94qoU8u7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkxnenJILzc2K1c4QzIw
            Q0JRekc1cktFYnZ0aHNkY0RaRFNrazUwemo0Cmt4MFlIeVNROGkrZEdrVVl6SjIw
            TDJZRmswbVo5VEtXc25Na1dtalRFcFkKLS0tIFpIV3VRWERZc2Y5UFlrY3Y4c3ph
            TCsyMDVpMTRtS2JSbnJRYlBwYWpZbmMKK3ks9xMl2UGmlFG0yxVUkoYMT4FYLUOy
            +RjhdBXGDqKVzHdciiHdJjl5NrZTxSg1EMHQJCbZjkbqyf7Bb9HPAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ca09pc0uh58kee7tsajs9yvjcfk3nhzu2k7c83n5h2j49r4wzu5sjy8vm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOFJUN1dFOEFGcmF0bzNu
            Q2Z1cmdRMC9VZHBRKzEybTJCazJMc1BGMjNnCjJSZnZDWFZwbFZRc3lkNzNhRGJ4
            bVRCSk9kMTBUaFdRL1FMUVFKSzZFS0UKLS0tIGZheUJydHI4QnN6b0tMQ1RabUNL
            VDUzeGJPR1lzUDBJMEcwWnp2c29nRFUKotZOC1rEYk4dY0VLG3kS8Ei7zZE4D0om
            TRjXH3CEH7mzXQp5RXZYVbLHw7MY21DWXvSQVmwVEigFUFsRmf/JPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-09T13:30:00Z"
    mac: ENC[AES256_GCM,data:j0CVjcGE+OY5aQ7+7tcQSD7rJ4orvCSJZlDT/qQ5YkOJkKECubKOE3SBmbA2jd1zuQAd0S/t/PyP0rIihKm1glVG6NLo0rV/L9vjcHa+BvTiLvk5co/Q3vMNF1L1aGiqnQYsJQYhMuL3PYLXZSc9N2Ew2b3wKPsfC2gasYblBs8=,iv:pOKaf9cQjkhsOEGqZv9suTUDrBqti1i3aOX9DbYgUMY=,tag:mrBYXXoVnjaTah8p48lbzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
