apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
    {{- if .Values.sablier.enabled }}
    sablier.enable: "true"
    sablier.group: {{ .Values.sablier.groupName }}
    {{- end }}
  name: {{ tpl .Values.fullName . }}
spec:
  selector:
    matchLabels:
      {{- tpl (.Values.commonLabels  | toYaml | nindent 6 ) $ }}
  template:
    metadata:
      labels:
        {{- tpl (.Values.commonLabels  | toYaml | nindent 8) $ }}
      annotations:
      {{- if .Values.config.nonSensitive }}
        checksum/configmap: {{ include (print $.Template.BasePath "/environment-configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.config.sensitive }}
        checksum/secret: {{ include (print $.Template.BasePath "/environment-secret.yaml") . | sha256sum }}
      {{- end }}
        argocd.argoproj.io/sync-wave: "1"
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" (dict "user" 101) | nindent 8 }}
      containers:
        {{- with $.Values.image }}
        - image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
        {{- end }}
          securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 12 }}
          imagePullPolicy: IfNotPresent
          name: projects-frontend
          ports:
            - name: http
              containerPort: {{ .Values.targetPort }}
          envFrom:
            {{- if .Values.config.nonSensitive }}
            - configMapRef:
                name: {{ tpl .Values.fullName . }}
            {{- end }}
          resources: {{- .Values.resources |toYaml | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
            httpGet:
              scheme: HTTP
              path: /
              port: http
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              scheme: HTTP
              path: /
              port: http
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ tpl $.Values.fullName $ }}
