apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
  name: {{ tpl .Values.fullName . }}
spec:
  selector:
    matchLabels:
      {{- tpl (.Values.commonLabels  | toYaml | nindent 6 ) $ }}
  template:
    metadata:
      labels:
        {{- tpl (.Values.commonLabels  | toYaml | nindent 8) $ }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        argocd.argoproj.io/sync-wave: "1"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        {{- with $.Values.image }}
        - image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
        {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          imagePullPolicy: IfNotPresent
          name: projects-frontend
          ports:
            - name: http
              containerPort: {{ .Values.targetPort }}
          env:
            - name: ADD_HEADER_HSTS
              value: add_header  Strict-Transport-Security "max-age=31536000" always;
            - name: NGINX_RESOLVER
              value: 10.0.0.10
          envFrom:
            {{- if .Values.injectedEnv.nonSensitive }}
            - configMapRef:
                name: {{ tpl .Values.fullName . }}
            {{- end }}
          resources: {{- .Values.resources |toYaml | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              scheme: HTTP
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              scheme: HTTP
              path: /
              port: http
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ tpl $.Values.fullName $ }}
