{{- if .Values.injectedEnv.nonSensitive }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ tpl .Values.fullName . }}
data:
{{- range $key, $val := .Values.injectedEnv.nonSensitive }}
  {{- if $key | contains "DOCKER_INJECT_" }}
    {{- fail (printf "DOCKER_INJECT_ prefix will be added automatically, remove it from %s" $key) }}
  {{- end }}
  {{- printf "DOCKER_INJECT_%s: %s" $key (tpl $val $ | quote) | nindent 2 -}}
{{- end }}
{{- end }}
