{{- if .Values.injectedEnv.sensitive }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ tpl .Values.fullName . }}
stringData:
{{- range $key, $val := .Values.injectedEnv.sensitive }}
  {{- if $key | contains "DOCKER_INJECT_" }}
    {{- fail (printf "DOCKER_INJECT_ prefix will be added automatically, remove it from %s" $key) }}
  {{- end }}
  {{- printf "DOCKER_INJECT_%s: %s" $key (tpl $val $) |nindent 2 -}}
{{ end -}}
{{ end -}}
