{{ include "common.security.networkPolicy" (dict
  "name" (tpl .Values.fullName .)
  "podSelector" (dict "matchLabels" (tpl (.Values.commonLabels | toJson) .| fromJson) )
  "allowFromNginx" true
) }}
