{{ include "common.security.networkPolicy" (dict
  "name" (tpl .Values.fullName .)
  "podSelector" (dict "matchLabels" (tpl (.Values.commonLabels | toJson) .| fromJson) )
  "allowFromReverseProxy" true
  "reverseProxyNamespace" (ternary "traefik" "ingress-nginx" .Values.traefik  )
  "enableEgress" false
  "commonLabels" (tpl (.Values.commonLabels | toJson) . | fromJson)
) }}
