apiVersion: v1
kind: Service
metadata:
  labels:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
  name: {{ tpl .Values.fullName . }}
{{- /* Allow passing a boolean as a string, for applicationset */}}
{{- /* https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#limitations*/}}\
spec:
{{- if eq "true" (.Values.maintenance.enabled | toString) }}
  type: ExternalName
  externalName: {{ printf "%s.%s" .Values.maintenance.serviceName .Values.maintenance.namespace }}
{{- else }}
  selector:
    {{- tpl (.Values.commonLabels  | toYaml | nindent 4 ) $ }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
{{- end }}
