import { PeopleModel } from '@/models/people.model'

export const peopleSkeleton = (def?: Partial<PeopleModel>): Omit<PeopleModel, 'id'> => ({
  slug: 'slug',
  roles: [],
  current_org_role: 'current_org_role',
  created_at: new Date().toISOString(),
  permissions: [],
  is_superuser: true,
  people_groups: [],
  notifications: 0,
  privacy_settings: {},
  skills: [],
  language: 'language',
  email: 'email',
  email_verified: true,
  given_name: 'given_name',
  family_name: 'family_name',
  birthday: new Date().toISOString(),
  pronouns: 'pronouns?',
  short_description: 'short_description?',
  description: 'description?',
  location: 'location?',
  job: 'job',
  mobile_phone: 'mobile_phone?',
  personnal_email: 'personnal_email',
  sdgs: [],
  facebook: 'facebook?',
  linkedin: 'linkedin?',
  medium: 'medium?',
  website: 'website?',
  skype: 'skype?',
  landline_phone: 'landline_phone?',
  twitter: 'twitter?',
  ...(def || {}),
})
