import type { UserModel } from 'shared-projects-frontend/models'

export const userSkeleton = (def?: Partial<UserModel>): UserModel => ({
  id: null,
  slug: 'slug',
  roles: [],
  permissions: [],
  email: 'email',
  given_name: 'given_name',
  family_name: 'family_name',
  pronouns: 'pronouns?',
  short_description: 'short_description?',
  description: 'description?',
  job: 'job',
  sdgs: [],
  facebook: null,
  is_superuser: false,
  linkedin: null,
  twitter: null,
  website: null,
  created_at: new Date().toISOString(),
  landline_phone: null,
  location: '',
  mobile_phone: null,
  modules: {
    conferences: 0,
    files: 0,
    follows_categories: 0,
    follows_projects: 0,
    groups: 0,
    links: 0,
    mentor: 0,
    mentoree: 0,
    projects: 0,
    publications: 0,
    skills: 0,
    notifications: 0,
  },
  skype: null,

  ...(def || {}),
})
