name: Build e2e Docker image

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    uses: CyberCRI/github-workflows/.github/workflows/build-push.yaml@main
    with:
      registry-name: ${{ vars.DOCKER_PROD_REGISTRY }}
      image-name: projects-frontend-e2e
      image-tag: ${{ github.sha }}
      recursive-submodule-checkout: true
      file: e2e.Dockerfile
    secrets:
      submodules-app-private-key: ${{ secrets.INFRA_BOT_APP_PRIVATE_KEY }}
      submodules-app-id: ${{ secrets.INFRA_BOT_APP_ID }}
      submodules-app-installation-id: ${{ secrets.INFRA_BOT_APP_INSTALLATION_ID }}
      registry-username: ${{ secrets.DOCKER_PROD_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PROD_PASSWORD }}
