name: Lint, test, build and push image

on:
  push:
    branches:
      - "*"
    tags:
      - "**"
      - "!**_deploy"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # lint-and-test:
  #   uses: ./.github/workflows/lint-and-test.yml
  build-docker:
    uses: CyberCRI/github-workflows/.github/workflows/build-push.yaml@main
    with:
      registry-name: ${{ vars.DOCKER_PROD_REGISTRY }}
      image-name: projects-front
      image-tag: ${{ github.sha }}
      recursive-submodule-checkout: true
      build-args: |
        VITE_APP_API_ORG_CODE=$DOCKER_INJECT_ORG_CODE
        VITE_APP_API_URL=$DOCKER_INJECT_VITE_APP_API_URL
        VITE_APP_BASE_URL=$DOCKER_INJECT_VITE_APP_BASE_URL
        VITE_APP_CAPTCHA_KEY=$DOCKER_INJECT_VITE_APP_CAPTCHA_KEY
        VITE_APP_DOC=$DOCKER_INJECT_VITE_APP_DOC
        VITE_APP_I18N_LOCALE=$DOCKER_INJECT_VITE_APP_I18N_LOCALE
        VITE_APP_KEYCLOAK_REALM=$DOCKER_INJECT_VITE_APP_KEYCLOAK_REALM
        VITE_APP_KEYCLOAK_CLIENT_ID=$DOCKER_INJECT_VITE_APP_KEYCLOAK_CLIENT_ID
        VITE_APP_KEYCLOAK_CLIENT_SECRET=$DOCKER_INJECT_VITE_APP_KEYCLOAK_CLIENT_SECRET
        VITE_APP_KEYCLOAK_URL=$DOCKER_INJECT_VITE_APP_KEYCLOAK_URL
        VITE_APP_META_PORTAL_URL=$DOCKER_INJECT_VITE_APP_META_PORTAL_URL
        VITE_APP_MIXPANEL_API_URL=$DOCKER_INJECT_VITE_APP_MIXPANEL_API_URL
        VITE_APP_MIXPANEL_PROJECT_TOKEN=$DOCKER_INJECT_VITE_APP_MIXPANEL_PROJECT_TOKEN
        VITE_APP_PUBLIC_BINARIES_PREFIX=${{ vars.PUBLIC_BINARIES_PREFIX }}
        VITE_APP_WSS_HOST=$DOCKER_INJECT_VITE_APP_WSS_HOST
        VITE_APP_VERSION=$DOCKER_INJECT_VITE_APP_VERSION
        VITE_APP_HOME=$DOCKER_INJECT_VITE_APP_HOME

    secrets:
      submodules-app-private-key: ${{ secrets.INFRA_BOT_APP_PRIVATE_KEY }}
      registry-username: ${{ secrets.DOCKER_PROD_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PROD_PASSWORD }}

  # tag-deploy:
  #   needs:
  #     - build-docker
  #     - lint-and-test
  #   uses: CyberCRI/github-workflows/.github/workflows/tag-deploy.yaml@main
  tag-deploy-fast:
    needs:
      - build-docker
    uses: CyberCRI/github-workflows/.github/workflows/tag-deploy-fast.yaml@main
  # e2e:
  #   if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/tags/auto_staging' }}
  #   uses: ./.github/workflows/e2e.yml
  #   secrets: inherit
  #   needs:
  #   - tag-deploy
