name: Lint & Test
on:
  workflow_call:
jobs:
  lint-and-test:
    runs-on: [self-hosted, m2c4-runner]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for https://github.com/wagoid/commitlint-github-action
      - name: Read node and npm versions from package.json
        uses: skjnldsv/read-package-engines-version-actions@v3
        id: package-engines-versions
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.package-engines-versions.outputs.nodeVersion }}'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Cache node_modules
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install the dependencies
        run: yarn install --frozen-lockfile
      - name: Check that prettier has been run on all files
        run: yarn format:check
      - name: Run the linter
        run: yarn lint:ci
      - name: Run the tests
        run: yarn test:unit:ci
      - name: Uninstall Yarn
        run: npm uninstall -g yarn
